name: Code Linter

on:
  workflow_call:
  

jobs:
  syntax-check:
    name: Syntax Check
    runs-on: self-hosted
    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        env:
          runner: self-hosted
        with:
          php-version: "8.1"
          coverage: none
          tools: composer
          extensions: mongodb,mbstring,gd
          
      - name: Use local linter
        run: echo "${PWD}/vendor/bin" >> $GITHUB_PATH
        
      - name: Run linters php codesniff
        uses: thiar/lint-action@master
        with:
          php_codesniffer: true
          # Optional: Ignore warnings
          php_codesniffer_args: "-n"
          php_stan: true
          continue_on_error: false,
          neutral_check_on_warning: true
